version: 1
disable_existing_loggers: true



formatters:
    standard:
      format: "%(levelname)s  %(name)s:%(lineno)d - %(message)s"
    error:
        format: "%(levelname)s <PID %(process)d:%(threadName)s> %(name)s.%(funcName)s(): %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: standard
        stream: ext://sys.stderr

root:
    level: DEBUG
    handlers: [console]
    propagate: no

loggers:
    m3u8_dl:
        level: DEBUG
        handlers: [console]
        propagate: no
