version: 1
disable_existing_loggers: true

formatters:
    standard:
      # format: '[%(levelname)-8s] %(filename)s:%(lineno)-5s  %(message)s'
      format: "%(module)s:%(lineno)-4s %(message)s"
    error:
        format: "[%(asctime)s]:%(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s():\n %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        formatter: standard

root:
    level: DEBUG
    handlers: [console]
    propagate: no

loggers:
    logx:
        level: DEBUG
        handlers: [console]
        propagate: no
    m3_dl:
        level: DEBUG
        handlers: [console]
        propagate: no

